# Generated by Django 3.0.6 on 2020-07-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='sexe',
        ),
    ]
